name: flutter_intl_eg
description: "A simple example application to explain flutter_intl"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated

flutter:
  uses-material-design: true
  generate: true
